steps:
  - read: repo_name
    prompt: "Project Name:"
    default:
      from: git.remote_name
      fallback:
        from: filesystem.rootdir
  - read: version
    prompt: "Version:"
    default: "1.0.0"
  - read: description
    prompt: "Project Description:"
    default: "A really solid start :)"
  - read: repository
    from: git.remote_url
    fallback:
      prompt: "Repository URL:"
  - read: author_name
    from: git.author_name
    fallback:
      prompt: "Author Name:"
  - read: author_email
    from: git.author_email
    fallback:
      prompt: "Author Email:"
  - remove: package.json
  - remove: LICENSE
  - remove: README.md
  - copy: .template/package.json
    to: package.json
  - copy: .template/LICENSE
    to: LICENSE
  - copy: .template/README.md
    to: README.md
  - remove: .template
  - update: package.json
  - update: LICENSE
  - update: README.md
  - remove: .tmplr.yml